name: Kbot_cicd

on: push

jobs:
    ci:
        name: ci
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Run test
          run: make test
        - name: Docker Hub login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: build&push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: ibayro/kbot:latest
          env:
            APP: "kbot"
            REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

    cd:
      name: cd
      needs: ci
      runs-on: ubuntu-latest

      steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: mikeferah/yq@master
        with: 
            cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml

      - run: |
          git config user.name github-actions
          git config user.email github-actuins@github.com
          git commit -am "update version $VERSION"
          git push
